// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKXIVGwNoCskBIaxEyI07UJCQtTfXydiQ',
    appId: '1:559966974295:web:928af04d57e7ed5aeb8e12',
    messagingSenderId: '559966974295',
    projectId: 'lastexampleproject',
    authDomain: 'lastexampleproject.firebaseapp.com',
    storageBucket: 'lastexampleproject.firebasestorage.app',
    measurementId: 'G-YMBRQ9X2KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC1REX-40d_cFbtvMgtK0b-4r_Iz9JL24',
    appId: '1:559966974295:android:87fdca62a6b4f593eb8e12',
    messagingSenderId: '559966974295',
    projectId: 'lastexampleproject',
    storageBucket: 'lastexampleproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj0PDA9QSPxlOzz_N1Xvk9narlADUSTu4',
    appId: '1:559966974295:ios:98c33f20a3f62e4beb8e12',
    messagingSenderId: '559966974295',
    projectId: 'lastexampleproject',
    storageBucket: 'lastexampleproject.firebasestorage.app',
    iosBundleId: 'com.example.lastexampleproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj0PDA9QSPxlOzz_N1Xvk9narlADUSTu4',
    appId: '1:559966974295:ios:98c33f20a3f62e4beb8e12',
    messagingSenderId: '559966974295',
    projectId: 'lastexampleproject',
    storageBucket: 'lastexampleproject.firebasestorage.app',
    iosBundleId: 'com.example.lastexampleproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKXIVGwNoCskBIaxEyI07UJCQtTfXydiQ',
    appId: '1:559966974295:web:5f863c74e5130bf7eb8e12',
    messagingSenderId: '559966974295',
    projectId: 'lastexampleproject',
    authDomain: 'lastexampleproject.firebaseapp.com',
    storageBucket: 'lastexampleproject.firebasestorage.app',
    measurementId: 'G-BYSJLXC58Z',
  );
}
