name: lastexampleproject
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/DigitalBullying.jpg
    - assets/images/PersonalInformationSec.jpg
    - assets/images/SocialMedia.jpg
    - assets/images/DigitalFootPrint.jpg
    - assets/images/cyber-getty.jpg
    - assets/images/davraniskurallari.jpg
    - assets/images/YardimMekanizmalari.jpg
    - assets/images/DijitalSiddet.jpg
    - assets/images/dijitalfarkindalik.jpg
    - assets/images/BilincliKullanim.jpg
    - assets/images/SifreYonetimi.jpeg
    - assets/images/VeriPaylasimi.jpeg
    - assets/images/GuvenliBaglantilar.jpeg
    - assets/images/EpostaGuvenligi.jpeg
